FROM python:3.11-slim

WORKDIR /loader

RUN apt-get update && \
    apt-get install -y unzip && \
    rm -rf /var/lib/apt/lists/*
    
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY load_data.py .

CMD ["python", "load_data.py"]